# Generated by Django 2.2.3 on 2019-07-18 10:42

from django.db import migrations, models
import django.db.models.deletion
import issues_linker.quickstart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_GH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=1, max_length=256)),
                ('body', models.CharField(blank=1, max_length=65536)),
                ('url', models.CharField(max_length=512)),
                ('id_gh', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'issue_fields_gh',
                'verbose_name': 'issue_field_gh',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Issue_GH_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Issue_RM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=1, max_length=256)),
                ('body', models.CharField(blank=1, max_length=65536)),
                ('id_rm', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'issue_fields_rm',
                'verbose_name': 'issue_field_rm',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Issue_RM_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Linked_Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_issue_rm', models.BigIntegerField(blank=1)),
                ('id_issue_gh', models.BigIntegerField(blank=1)),
                ('id_repo_gh', models.BigIntegerField(blank=1)),
                ('num_issue_gh', models.BigIntegerField(blank=1)),
            ],
            options={
                'verbose_name_plural': 'linked_issues',
                'verbose_name': 'linked_issues',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Linked_Issues_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project_RM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rm', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'projects_rm',
                'verbose_name': 'project_rm',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Project_RM_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Repository_GH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gh', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'repositories_gh',
                'verbose_name': 'repository_gh',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Repository_GH_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payload_RM_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=1, max_length=20)),
                ('issue', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Issue_RM')),
            ],
            options={
                'verbose_name_plural': 'payload_fields_from_rm',
                'verbose_name': 'payload_field_from_rm',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Payload_RM_Field_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payload_RM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_field', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Payload_RM_Field')),
            ],
            options={
                'verbose_name_plural': 'payloads_from_rm',
                'verbose_name': 'payload_from_rm',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Payload_RM_Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payload_GH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=1, max_length=20)),
                ('issue', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Issue_GH')),
                ('repository', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Repository_GH')),
            ],
            options={
                'verbose_name_plural': 'payloads_from_gh',
                'verbose_name': 'payload_from_gh',
            },
            managers=[
                ('objects', issues_linker.quickstart.models.Payload_GH_Manager()),
            ],
        ),
        migrations.AddField(
            model_name='issue_rm',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Project_RM'),
        ),
    ]
