# Generated by Django 2.2.3 on 2019-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linked_issues',
            name='id_issue_gh',
            field=models.BigIntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='linked_issues',
            name='id_issue_rm',
            field=models.BigIntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='linked_issues',
            name='id_repo_gh',
            field=models.BigIntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='linked_issues',
            name='num_issue_gh',
            field=models.BigIntegerField(blank=1, null=1),
        ),
    ]
