# Generated by Django 2.2.3 on 2019-07-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190718_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linked_issues',
            old_name='id_issue_gh',
            new_name='issue_id_gh',
        ),
        migrations.RenameField(
            model_name='linked_issues',
            old_name='id_issue_rm',
            new_name='issue_id_rm',
        ),
        migrations.RenameField(
            model_name='linked_issues',
            old_name='id_repo_gh',
            new_name='issue_num_gh',
        ),
        migrations.RenameField(
            model_name='linked_issues',
            old_name='num_issue_gh',
            new_name='repos_id_gh',
        ),
    ]
